# Template for node see:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
# Coverage see:
# https://gist.github.com/rishitells/3c4536131819cff4eba2c8ab5bbb4570

image: node:20

# variables:
#   DOCKER_HOST: tcp://docker:2376

stages:
  - test
  - build
  # - deploy

test_backend:
  stage: test
  variables:
    # BHT's Gitlab CI only supports MongoDB up to 7.0.3
    MONGOMS_VERSION: "7.0.3"
  script:
    - cd backend
    - npm ci
    - npm test
  artifacts:
    reports:
      junit:
        - backend/junit.xml

test_frontend:
  # stage: test
  # variables:
  #   # BHT's Gitlab CI only supports MongoDB up to 7.0.3
  #   MONGOMS_VERSION: "7.0.3"
  script:
    - cd frontend
    - npm install
    # - npm test
  # artifacts:
  #   reports:
  #     junit:
  #       - frontend/junit.xml

build_backend:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'dev'
  stage: build

  image: docker:20.10.16
  services:
    - name: registry.hub.docker.com/library/docker:20.10.16-dind
      alias: docker
  tags:
    - docker-privileged
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # - echo $CI_REGISTRY
    # - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/jala5026/kimbaa/backend:$CI_COMMIT_REF_SLUG backend/
    - docker push $CI_REGISTRY/jala5026/kimbaa/backend:$CI_COMMIT_REF_SLUG


build_frontend:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'dev'
  stage: build
  needs: ["test_frontend"]
  image: docker:20.10.16
  services:
    - name: registry.hub.docker.com/library/docker:20.10.16-dind
      alias: docker
  tags:
    - docker-privileged
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/jala5026/kimbaa/frontend:$CI_COMMIT_REF_SLUG frontend/
    - docker push $CI_REGISTRY/jala5026/kimbaa/frontend:$CI_COMMIT_REF_SLUG

# build_frontend_prod:
#   stage: build
#   script:
#     - cd frontend
#     - npm install
#     - npm run build
