version: "3"

services:
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      - BPORT=8081
    networks:
      - loki

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/backend
      - ./backend/cert:/backend/cert
    ports:
      - "8081:3000"  # HTTP Port
      - "8444:3001"  # HTTPS Port (Mapping des internen 3443 auf externen 8443)
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/
      - HTTP_PORT=3000
      - FRONTEND_PORT=3000
      - USE_SSL=true
      - HTTPS_PORT=3001
      - SSL_KEY_FILE=/backend/cert/private.key
      - SSL_CRT_FILE=/backend/cert/public.crt
    depends_on:
      - mongo
    networks:
      - loki

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - mongodb/mongo-dev.env
    networks:
      - loki

networks:
  loki:
