# Use root/example as user/password credentials
# From:
# https://hub.docker.com/_/mongo/

version: '3.1'

services:

  frontend:
    build:
      context: frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: #TODO target path
          ignore: 
            - ./frontend/package.json
        - action: rebuild
          path: ./backend/package.json

 




  backend:
    build:
      contex: backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: #TODO target path
          ignore: 
            - ./backend/package.json
            - ./backend/tests
            - ./backend/testConfig
        - action: rebuild
          path: ./backend/package.json

    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports: 
      - '27017:27017'
    env_file:
      - mongodb/mongo-dev.env

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: false


networks:
  kimbaa:
    name: kimbaa
