---
version: "3"

services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=localhost
      - HTTP_PORT=3000
      - HTTPS_PORT=3443
      - HTTPS=true
      - BACKEND_URL=https://localhost:3443 # oder die entsprechende URL
    networks:
      - loki

  backend:
    build:
      context: backend
    ports:
      - "8081:3000"
      - "3443:3443"
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/
      - HTTP_PORT=3000
      - FRONTEND_PORT=3000
      - USE_SSL=true
      - HTTPS_PORT=3443
      - SSL_KEY_FILE=/backend/cert/private.key
      - SSL_CRT_FILE=/backend/cert/public.crt
    volumes:
      - ./backend:/backend
      - ./backend/cert:/backend/cert
    depends_on:
      - mongo
    networks:
      - loki

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - mongodb/mongo-dev.env
    networks:
      - loki

networks:
  loki:
