#kimbaa stack
---
version: "3"

services:

  frontend:
    build:
      context: frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend #TODO target path
          ignore:
            - ./frontend/package.json
        - action: rebuild
          path: ./backend/package.json
    ports:
      - 3000:3000
    environment:
    - REACT_APP_HOSTNAME=localhost
    - REACT_APP_PORT=8081
    - FRONTEND_PORT=3000
    networks:
      - loki

  backend:
    build:
      context: backend
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend #TODO target path
          ignore:
            - ./backend/package.json
            - ./backend/tests
            - ./backend/testConfig
        - action: rebuild
          path: ./backend/package.json
    ports:
      - 8081:3000
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/
      - HTTP_PORT=3000
      - HOSTNAME=localhost
      - FRONTEND_PORT=3000
    depends_on:
      - mongo
    networks:
      - loki

  mongo:
    container_name: mongo-db
    image: mongo
    # image: mongodb-raspberrypi4-unofficial-r7.0.4
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - mongodb/mongo-dev.env
    networks:
      - loki

networks:
  loki:
