apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimbaa-backend
  labels:
    app: kimbaa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimbaa-backend
  template:
    metadata:
      labels:
        app: kimbaa-backend
    spec:
      containers:
      - name: kimbaa-backend
        image: kimbaa-backend #TODO: fix image
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000
