apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimbaa-backend
  labels:
    app: kimbaa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimbaa-backend
  template:
    metadata:
      labels:
        app: kimbaa-backend
    spec:
      containers:
      - name: kimbaa-backend
        image: kimbaa-backend #TODO: fix image
        ports:
        - containerPort: 3000
        - containerPort: 3443
---
apiVersion: v1
kind: Service
metadata:
  name: kimbaa-backend-service
spec:
  selector:
    app: kimbaa-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 443
      targetPort: 3443
