# Use root/example as user/password credentials
# From:
# https://hub.docker.com/_/mongo/

version: '3.1'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    ports: 
      - '27017:27017'
    env_file:
      - mongo-dev.env

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: false


networks:
  kimbaa:
    name: kimbaa
